services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - 5433:5432
